USPACE_PREFIX = ../..


# TODO: Should be just "AppKit", rest is transitive dependencies. "AppKit" needs to stay first !
LIBS =  AppKit gui draw softrend compress  math

BINARY = vizctl
SOURCES = vizctl.c AKScreen.c
include $(USPACE_PREFIX)/Makefile.common
